---
version: 2.8.2
commit: 'chore(version): bump to v%.%.%'
files:
  README.md:
  - coveralls-gradle-plugin v%.%.%
  - id 'com.github.kt3k.coveralls' version '%.%.%'
  build.gradle:
  - name = '%.%.%'
  - vcsTag = 'v%.%.%'
  - version '%.%.%'
